/** Icon names CMS content may use. Rendered by src/components/ui/Icon.tsx. */
export const ICON_NAMES = [
  "Activity",
  "Award",
  "BarChart",
  "BookOpen",
  "Briefcase",
  "CheckCircle",
  "ClipboardCheck",
  "Clock",
  "Code",
  "Compass",
  "DollarSign",
  "FileText",
  "Globe",
  "GraduationCap",
  "Heart",
  "HeartHandshake",
  "Layers",
  "Lightbulb",
  "Mail",
  "MapPin",
  "Megaphone",
  "Monitor",
  "MousePointerClick",
  "Palette",
  "Phone",
  "PhoneCall",
  "Plane",
  "Rocket",
  "Search",
  "Settings",
  "Shield",
  "ShoppingBag",
  "Star",
  "Tag",
  "Target",
  "TrendingUp",
  "Users",
  "Wrench",
  "Zap",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
