import { createElement } from "react";
import {
  Activity,
  Award,
  BarChart3,
  BookOpen,
  Briefcase,
  CheckCircle2,
  ClipboardCheck,
  Clock,
  Code2,
  Compass,
  DollarSign,
  FileText,
  Globe,
  GraduationCap,
  Heart,
  HeartHandshake,
  Layers,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  Monitor,
  MousePointerClick,
  Palette,
  Phone,
  PhoneCall,
  Plane,
  Rocket,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  Star,
  Tag,
  Target,
  TrendingUp,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import { ICON_NAMES, type IconName } from "@/lib/content/icons";

/** Icons that CMS content can reference by name. Keep in sync with ICON_NAMES. */
const ICONS: Record<IconName, LucideIcon> = {
  Activity,
  Award,
  BarChart: BarChart3,
  BookOpen,
  Briefcase,
  CheckCircle: CheckCircle2,
  ClipboardCheck,
  Clock,
  Code: Code2,
  Compass,
  DollarSign,
  FileText,
  Globe,
  GraduationCap,
  Heart,
  HeartHandshake,
  Layers,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  Monitor,
  MousePointerClick,
  Palette,
  Phone,
  PhoneCall,
  Plane,
  Rocket,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  Star,
  Tag,
  Target,
  TrendingUp,
  Users,
  Wrench,
  Zap,
};

const isIconName = (name: string): name is IconName => (ICON_NAMES as readonly string[]).includes(name);

/** Renders a CMS icon by name; unknown names fall back to a wrench. */
export default function Icon({ name, ...props }: LucideProps & { name: string }) {
  return createElement(isIconName(name) ? ICONS[name] : Wrench, props);
}
